
package gui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import oop6.Medico;
import oop6.Sistema;

public class PainelConsultasMedico extends javax.swing.JFrame {
    Sistema sistema_painel_consulta_paciente;
    Medico medico;
    
    public PainelConsultasMedico() {
        medico = new Medico();
        sistema_painel_consulta_paciente = new Sistema();
        initComponents();
        this.setLocationRelativeTo(null);
        tabelaConsultas.setDefaultEditor(Object.class, null);
        tabelaConsultas.getTableHeader().setReorderingAllowed(false);
    }
    
    public void setMedico(Medico novo_medico){
        this.medico = novo_medico;
    }
    
    public Medico getMedico(){
        return this.medico;
    }
    
    public void carrega_consultas(){
        DefaultTableModel model = (DefaultTableModel) tabelaConsultas.getModel();
        for(int i = 0; i < this.sistema_painel_consulta_paciente.lista_consultas.size(); i++){
            if(this.medico.getNome().compareTo(this.sistema_painel_consulta_paciente.lista_consultas.get(i).get_nome_medico()) == 0){
                model.addRow(recupera_dados(i));
            }
        }
    }
    
    public String[] recupera_dados(int i){
        List<String> dados = new ArrayList<>();
        String nome_paciente = this.sistema_painel_consulta_paciente.lista_consultas.get(i).get_nome_paciente();
        LocalDate date = this.sistema_painel_consulta_paciente.lista_consultas.get(i).get_data(); 
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MM yyyy");
        String data = date.format(formatter);
        String sala = this.sistema_painel_consulta_paciente.lista_consultas.get(i).get_sala();
        String valor = Float.toString(this.sistema_painel_consulta_paciente.lista_consultas.get(i).get_valor());
        String numero = Integer.toString(this.sistema_painel_consulta_paciente.lista_consultas.get(i).getID());
        dados.add(nome_paciente);
        dados.add(data);
        dados.add(sala);
        dados.add(valor);
        dados.add(numero);
        String[] stringArray = dados.toArray(new String[0]);
        return stringArray;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Data", "Sala", "Valor", "Número"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaConsultas);
        tabelaConsultas.getAccessibleContext().setAccessibleName("s");

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Consultas Marcadas");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(296, 296, 296))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(botaoVoltar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        PainelMedico painel_medico = new PainelMedico();
        painel_medico.setMedico(this.medico);
        painel_medico.sistema_painel_medico.carrega_listas(this.sistema_painel_consulta_paciente.lista_funcionarios, this.sistema_painel_consulta_paciente.lista_pacientes);
        painel_medico.sistema_painel_medico.carrega_listas_medicas(this.sistema_painel_consulta_paciente.lista_consultas, this.sistema_painel_consulta_paciente.lista_atestados);
        painel_medico.setMedico(this.getMedico());
        painel_medico.setLabels();
        painel_medico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelConsultasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelConsultasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelConsultasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelConsultasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelConsultasMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaConsultas;
    // End of variables declaration//GEN-END:variables
}
